### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [CHG-MERIDIAN/CHG.Extensions.Security.Txt#37]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by twenzel** [comment]
It uses Appveyor.
Why do you ask?

**Comment by guilhermeddf** [comment]
@twenzel I'm doing research about CI Tools. Thank you.
