### ISSUE TITLE
Implementing redirects

### ISSUE THREAD

**Issue by JackGilmore** [CHG-MERIDIAN/CHG.Extensions.Security.Txt#43]
**Is your feature request related to a problem? Please describe.**
The RFC for security.txt supports redirects e.g. from app.example.com/.well-known/security.txt to example.com/.well-known/security.txt or from another-example.com//.well-known/security.txt to example.com/.well-known/security.txt

**Describe the solution you'd like**
Would you support a new feature to allow this? Possible implementations I was thinking of include:

Service registration that passes in a Uri to redirect to
```c#
builder.Services.AddSecurityText(new Uri("https://example.com/.well-known/security.txt"));
```

OR using the existing TextBuilder approach
```c#
builder.Services.AddSecurityText(textBuilder =>
{
	textBuilder
		.SetRedirect(new Uri("https://example.com/.well-known/security.txt"))
});
```

**Describe alternatives you've considered**
None

**Additional context**
I'm happy to work on this and submit a pull request if you agree to the feature's implementation.

**Comment by twenzel** [comment]
Looks good to me. I'm looking forward to your PR.

**Comment by JackGilmore** [comment]
@twenzel PR in under #44
